###
POST http://localhost:8080/database/range
Content-Type: application/json

{
  "address": 16,
  "register": 1,
  "from": "2022-05-08T15:30:00",
  "to": "2022-05-08T15:33:00"
}
###
GET http://localhost:8080/database/get-last-row?address=16&register=1
Accept: application/json
###
GET http://localhost:8080/database/get-current-date-time
Accept: application/json
###
GET http://localhost:8080/modbus/read-all
Accept: application/json
###
GET http://localhost:8080/modbus/read-one?address=16&register=1
Accept: application/json
###
GET http://localhost:8080/modbus/write-one?address=16&register=1&value=34.1
Accept: application/json
###
POST http://localhost:8080/modbus/write-config-device
Content-Type: application/json

{
  "cache": [
    {
      "address": 16,
      "register": 0,
      "write": true,
      "archive": true,
      "hysteresis": "1",
      "value": "0",
      "oldValue": "0",
      "registerRange": 3,
      "offset": 0,
      "dataType": 2
    },
    {
      "address": 16,
      "register": 1,
      "write": true,
      "archive": true,
      "hysteresis": "1",
      "value": "0",
      "oldValue": "0",
      "registerRange": 3,
      "offset": 1,
      "dataType": 8
    },
    {
      "address": 16,
      "register": 4,
      "write": true,
      "archive": true,
      "hysteresis": "1",
      "value": "0",
      "oldValue": "0",
      "registerRange": 4,
      "offset": 4,
      "dataType": 8
    },
    {
      "address": 16,
      "register": 10,
      "write": true,
      "archive": true,
      "hysteresis": "1",
      "value": "0",
      "oldValue": "0",
      "registerRange": 4,
      "offset": 10,
      "dataType": 8
    },
    {
      "address": 24,
      "register": 0,
      "write": true,
      "archive": true,
      "hysteresis": "1",
      "value": "0",
      "oldValue": "0",
      "registerRange": 3,
      "offset": 0,
      "dataType": 2
    },
    {
      "address": 24,
      "register": 4,
      "write": true,
      "archive": true,
      "hysteresis": "1",
      "value": "0",
      "oldValue": "0",
      "registerRange": 4,
      "offset": 4,
      "dataType": 8
    },
    {
      "address": 24,
      "register": 10,
      "write": true,
      "archive": true,
      "hysteresis": "1",
      "value": "0",
      "oldValue": "0",
      "registerRange": 4,
      "offset": 10,
      "dataType": 8
    }
  ]
}
###
GET http://localhost:8080/modbus/read-config-device
Accept: application/json
###
POST http://localhost:8080/modbus/write-config-modbus-serial
Content-Type: application/json

{
  "port": "/dev/ttyUSB0",
  "baduRate": 9600,
  "dataBits": 8,
  "stopBits": 1,
  "parity": 0,
  "timeout": 200,
  "retries": 1
}
###
GET http://localhost:8080/modbus/read-config-modbus-serial
Accept: application/json
###
POST http://localhost:8080/modbus/write-config-modbus-tcp
Content-Type: application/json

{
  "host": "localhost",
  "port": 2222,
  "timeout": 200,
  "retries": 1
}
###
GET http://localhost:8080/modbus/read-config-modbus-tcp
Accept: application/json
###
GET http://localhost:8080/chain/modbus
Accept: application/json